### ISSUE TITLE
Make the Vue project

### ISSUE THREAD

**Issue by AngelGarcia13** [AngelGarcia13/DominicanWhoCodes#11]
The idea behind DominicanWho.Codes was use this project to learn how to use the main JS front-end frameworks.

That's why I'm doing the same thing with Vue.

**Comment by DannyFeliz** [comment]
Vue ❤️

**Comment by lewandy** [comment]
Some api will be created?

**Comment by AngelGarcia13** [comment]
@lewandy yes! Tomorrow we will be publishing the roadmap to give a general idea of what’s going on with this project.

Did you send your profile info? If not please make a PR to adding yourself to the developers.json file in the data folder (under wwroot), same for you bro @DannyFeliz

**Comment by DannyFeliz** [comment]
> @lewandy yes! Tomorrow we will be publishing the roadmap to give a general idea of what’s going on with this project.
> 
> Did you send your profile info? If not please make a PR to adding yourself to the developers.json file in the data folder (under wwroot), same for you bro @DannyFeliz

Will do today @AngelGarcia13 👌

**Comment by AngelGarcia13** [comment]
> @lewandy yes! Tomorrow we will be publishing the roadmap to give a general idea of what’s going on with this project.
> 
> Did you send your profile info? If not please make a PR to adding yourself to the developers.json file in the data folder (under wwroot), same for you bro @DannyFeliz

@lewandy there is already a roadmap added to the project, go and check it out!

**Comment by AngelGarcia13** [comment]
> > @lewandy yes! Tomorrow we will be publishing the roadmap to give a general idea of what’s going on with this project.
> > Did you send your profile info? If not please make a PR to adding yourself to the developers.json file in the data folder (under wwroot), same for you bro @DannyFeliz
> 
> Will do today @AngelGarcia13 👌

😢 Waiting for you

**Comment by lewandy** [comment]
@AngelGarcia13 Nice!, let me go check.

**Comment by lewandy** [comment]
@AngelGarcia13 , the design have to be the same in the all frameworks or can be diferent?

**Comment by Avto9711** [comment]
@AngelGarcia13 @DannyFeliz  How we gonna do this? we'll only create a vue project with the same design and connected to the same data source  (JSON file)?

**Comment by AngelGarcia13** [comment]
> @AngelGarcia13 @DannyFeliz How we gonna do this? we'll only create a vue project with the same design and connected to the same data source (JSON file)?

Yes, let's keep the same UI/UX, this way the design issues would be the same for every client.

**Comment by AngelGarcia13** [comment]
@Avto9711 If you want to talk more about this, let's discuss in the Slack, create a Vue channel.

**Comment by DannyFeliz** [comment]
@AngelGarcia13 @Avto9711 @lewandy Here is the organization, I'm inviting you now.
https://github.com/orgs/VueDominicana

**Comment by DannyFeliz** [comment]
En Vue Dominicana we're on fire 🔥 

🚀 Netlify: https://dominicanwhocodes.netlify.com
💻 Repo: https://github.com/VueDominicana/DominicanWhoCodes
