### ISSUE TITLE
Show the current year in footer

### ISSUE THREAD

**Issue by nminaya** [AngelGarcia13/DominicanWhoCodes#120]
https://github.com/AngelGarcia13/DominicanWhoCodes/blob/8678119de264902d25a2c91218e51f49c9ade6cf/DWC.Blazor/Shared/MainLayout.razor#L45

We could get the current year from DateTime.Now.

**Comment by Jadhielv** [comment]
Done @nminaya, @AngelGarcia13 watch the PR #142
