### ISSUE TITLE
API to feed the apps

### ISSUE THREAD

**Issue by Garibaldy** [AngelGarcia13/DominicanWhoCodes#121]
Probably  a JSON (REST/JSON-API) format

**Comment by nminaya** [comment]
@Garibaldy The [json file](https://github.com/AngelGarcia13/DominicanWhoCodes/blob/master/DWC.Blazor/wwwroot/data/developers.json) of developers is public. I think you could use that as the API to get the developers info.

**Comment by Garibaldy** [comment]
Agree , but that depends of the uses cases, right now is just okay
