### ISSUE TITLE
Migration to current stable version need it

### ISSUE THREAD

**Issue by sgermosen** [AngelGarcia13/DominicanWhoCodes#124]
Recently I was trying to make filter by skills but, I get some errors by the version of the library I had installed on my computer, so, when I try to get the specific nuget, I found than almost all dependencies are deprecated 

As you can see here: https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Build/3.0.0-preview5-19227-01 

Microsoft.AspNetCore.Blazor.Build is replaced by Microsoft.AspNetCore.Components.WebAssembly.Build

as you can see here https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.DevServer/3.0.0-preview7.19365.7

Microsoft.AspNetCore.Blazor.DevServer is replaced by Microsoft.AspNetCore.Components.WebAssembly.DevServer

Microsoft.AspNetCore.Blazor.HttpClient is still working on preview, but, the current version only work with ASpNetCore, and that was a problem than stop me to work, I try to migrated the solution following those steps:https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/ 

but this migration its only for a netcore project, so, in this particular case, I think than the better alternative its create a new solution on stable version

**Comment by AngelGarcia13** [comment]
Thanks!
