### ISSUE TITLE
Card image not showing (Rancell Tapia)

### ISSUE THREAD

**Issue by Jadhielv** [AngelGarcia13/DominicanWhoCodes#145]
https://github.com/AngelGarcia13/DominicanWhoCodes/blob/618ab9d99fea69d6ea52eac74a5f1c68e25a2eaa/DWC.Blazor/wwwroot/data/developers.json#L687

![imagen](https://user-images.githubusercontent.com/24376900/92315261-ee543500-efb0-11ea-9a34-cb4397e1a9a7.png)

We could change the current format to **.jpg** | @RancellTapia **image** exists, view details:

![imagen](https://user-images.githubusercontent.com/24376900/92315301-a71a7400-efb1-11ea-8bf1-e68ee51cb82e.png)

**Comment by RancellTapia** [comment]
Format image updated.

**Comment by Jadhielv** [comment]
![image](https://user-images.githubusercontent.com/24376900/92811976-f33c2e80-f38c-11ea-9037-0f7fe09ab2ea.png)

Done .
