### ISSUE TITLE
Improve initial loading

### ISSUE THREAD

**Issue by GabrielBB** [AngelGarcia13/DominicanWhoCodes#16]
Isn't that "loading" slow for such a simple app? Is it because of Blazor or maybe the app not running in production mode? Or maybe just server limitations? If it can't be improved consider adding a better loading screen. You probably know this already but i'm just documenting the issue hehe

**Comment by AngelGarcia13** [comment]
Thanks for the comment, it's because of WebAssembly in general, it would be nice to have a better loading screen like you said.

I'm putting a label (help needed) for this issue.

**Comment by juanchinovas** [comment]
Yeah this is because load WebAssembly take some time, I just added a splash screen and create a pull request.

**Comment by GabrielBB** [comment]
Umm, I see. WebAssembly is over kill for a project like this in my opinion. But well, it works

**Comment by AngelGarcia13** [comment]
> Umm, I see. WebAssembly is over kill for a project like this in my opinion. But well, it works. UI looking good

Yeh, I know, it's just for have fun and learn Blazor.

I'm also planning to clone the same app in Angular(#10), React(#9) and Vue(#11).
