### ISSUE TITLE
Put a nice description in the top of the page

### ISSUE THREAD

**Issue by AngelGarcia13** [AngelGarcia13/DominicanWhoCodes#19]
I'm not that good writing nice descriptions, if you are reading this you know what's this project about, so write down a cool description.

**Comment by mecm1993** [comment]
I ain't good at writing either, but, a couple of options:

 - **TL;DR** Developers from a Caribbean island.
 - **TL;DR** Dominican developers who like to code and the Open Source.
 - **TL;DR** Developers from the Dominican Republic.

**Comment by AngelGarcia13** [comment]
@mecm1993 I like the second one!

**Comment by robertlluberes** [comment]
I Will work is this small Issue.
