### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by AngelGarcia13** [AngelGarcia13/DominicanWhoCodes#20]
We are good devs, let's write unit tests to this Blazor app.

**Comment by nminaya** [comment]
@AngelGarcia13 This project (DWC.Blazor.csproj) needs to be inside a Solution (.sln), so that we can add a unit test project

**Comment by AngelGarcia13** [comment]
Cool! Go ahead, we are open to solutions

**Comment by Jadhielv** [comment]
Closes #126 @AngelGarcia13
