### ISSUE TITLE
Make social media icons further apart

### ISSUE THREAD

**Issue by LeidiFlores** [AngelGarcia13/DominicanWhoCodes#209]
## Problem description

Currently social media icons have no space between them and look like this

![image](https://user-images.githubusercontent.com/62189355/197120848-f2474dfe-393f-4448-a67a-3f4e69d82697.png)

I think the page looks nicer and cleaner if the icons look like this with space

![image](https://user-images.githubusercontent.com/62189355/197121345-33411954-1872-4734-8022-f5e95c6ce0a5.png)

## Solution propose

So for that I considered making a class and corresponding css.

## Expected result

![image](https://user-images.githubusercontent.com/62189355/197122075-93d85c38-7b91-4b04-b8bc-f37b39e0b8ed.png)

**Comment by Jadhielv** [comment]
@LeidiFlores go ahead.

**Comment by udaykahar** [comment]
Hi, I can work on this, can you please assign me?

**Comment by LeidiFlores** [comment]
> @LeidiFlores go ahead.

https://github.com/AngelGarcia13/DominicanWhoCodes/pull/211 ready here! :)

**Comment by Jadhielv** [comment]
@udaykahar I unassigned this issue because was fixed by @LeidiFlores
