### ISSUE TITLE
Updating the navbar

### ISSUE THREAD

**Issue by Anurag-Singh-04** [AngelGarcia13/DominicanWhoCodes#210]
Hey @Jadhielv  There is not so much spacing in between the about and nominate button.

Before : 

<img width="1440" alt="Screenshot 2022-10-21 at 1 06 10 PM" src="https://user-images.githubusercontent.com/97782687/197140080-85247146-bcdd-42cb-a26d-d41182439a6c.png">

After : 

<img width="1440" alt="Screenshot 2022-10-21 at 1 06 35 PM" src="https://user-images.githubusercontent.com/97782687/197140338-ef1f66f4-90b7-4ac4-b7e7-ee428e03bc61.png">

Can you please assign me this issue.

**Comment by Anurag-Singh-04** [comment]
Hey @Jadhielv can you please label the issue with Hacktoberfest label.

**Comment by Jadhielv** [comment]
@Anurag-Singh-04 done.

**Comment by srijoy-paul** [comment]
Can you assign me this issue @Jadhielv ?

**Comment by Jadhielv** [comment]
Hey!! @srijoy-paul, @Anurag-Singh-04 is working on this issue. If he confirms that not have a chance to complete it, maybe I can assign it to you.

**Comment by srijoy-paul** [comment]
Sure! @Jadhielv

**Comment by srijoy-paul** [comment]
Hey @Jadhielv is he still working on this?

**Comment by Jadhielv** [comment]
@srijoy-paul apparently no, go ahead.

**Comment by Jadhielv** [comment]
@srijoy-paul I know Hacktoberfest 2022 is over, if considered completing this issue anyway, please let me know.

**Comment by Jadhielv** [comment]
Well no answers, @LeidiFlores if you've got the chance, please take a look at this issue.

**Comment by LeidiFlores** [comment]
hi @Jadhielv ! is it still necessary?

**Comment by Jadhielv** [comment]
yep @LeidiFlores. Do you want me to assign it to you?

**Comment by LeidiFlores** [comment]
yes, I work on it :)

**Comment by LeidiFlores** [comment]
ready on https://github.com/AngelGarcia13/DominicanWhoCodes/pull/219!
