### ISSUE TITLE
GitHub url duplicated

### ISSUE THREAD

**Issue by robertlluberes** [AngelGarcia13/DominicanWhoCodes#31]
The @dionnyprensa profile has the same GitHub URL as @AngelGarcia13 , this was pointed out in PR #28, but it was not resolved.

![image](https://user-images.githubusercontent.com/13991439/64277875-66f56100-cf19-11e9-8ffa-628c80f35b3a.png)

**Comment by AngelGarcia13** [comment]
Thanks @robertlluberes
