### ISSUE TITLE
Create a session to share technical thought.

### ISSUE THREAD

**Issue by aperez011** [AngelGarcia13/DominicanWhoCodes#48]
This session is for espouse an arguments about  latest technologies and frameworks to be implemented, where we can see the good and bad about them.

**Comment by AngelGarcia13** [comment]
We could use Slack, I’ll create it

**Comment by AngelGarcia13** [comment]
Here is our Slack @aperez011 

https://join.slack.com/t/dominicanwhocodes/shared_invite/enQtNzU0MjQ2OTY1MDk1LTcyMTUwODJkNTM2ZTQwYTQ0OWM4ODc4ZTBiOWU1N2Q0ZGY5NmJjZjExZjBjNTE0NGQ2ZjVjZTM2MDBjNmMzNDc

**Comment by AngelGarcia13** [comment]
> Here is our Slack @aperez011
> 
> https://join.slack.com/t/dominicanwhocodes/shared_invite/enQtNzU0MjQ2OTY1MDk1LTcyMTUwODJkNTM2ZTQwYTQ0OWM4ODc4ZTBiOWU1N2Q0ZGY5NmJjZjExZjBjNTE0NGQ2ZjVjZTM2MDBjNmMzNDc

Feel free to close the issue
