### ISSUE TITLE
[Discussion] List of skills and maximum skills per developer 

### ISSUE THREAD

**Issue by mecm1993** [AngelGarcia13/DominicanWhoCodes#69]
For a better coherence and organization, it could be beneficial to have a **list of skills** (languages, framework, etc.). So far, everyone has added there skills without any kind of filter.

If we take into consideration how IndiansWhoDesign is doing it, they have a list of "**categories**"/"**skills**"/"**positions**" which allow them to filter the list in a clean way and the designer has to categorize herself/himself to those skills. 

On the other hand, there should be a **max capacity of skills** per developer due to on some point someone could add more than five skills, or in another case, someone added three skills in a couple of months that person wants to update his/her skills because he/she learned a new one.

This is my opinion so far, I would like to know what you think.

**Comment by AngelGarcia13** [comment]
@ManuHernandez @robertlluberes What do you think?

**Comment by robertlluberes** [comment]
I think that both the fixed list and the amount of skills are fine, the difficult thing is to select that fixed list of skills.

How could that be handled, the maximum amount of skills, since we are talking about json file? Could that add complexity?

**Comment by AngelGarcia13** [comment]
> I think that both the fixed list and the amount of skills are fine, the difficult thing is to select that fixed list of skills.
> 
> How could that be handled, the maximum amount of skills, since we are talking about json file? Could that add complexity?

We could handle taking the first 3 or 4 from the array in the foreach at the CardComponent, but for now I think it's ok how is implemented now (with the horizontal scroll)

**Comment by Jadhielv** [comment]
@mecm1993 based on the last comment made by @AngelGarcia13, I'll be proceed with the closing at this issue. If you have time please confirm.

**Comment by mecm1993** [comment]
@Jadhielv ok, no problem
