### ISSUE TITLE
Explore hosting options for the project static sites

### ISSUE THREAD

**Issue by AngelGarcia13** [AngelGarcia13/DominicanWhoCodes#8]
Right now we have the project running in an Azure Web App (with a CI/CD pipeline with Azure DevOps), but it's only a static website, let's discuss some options to move the projects.

**Comment by mecm1993** [comment]
Options for static sites:

 - [Netlify](https://www.netlify.com/)
 - [Surge](https://surge.sh/)
 - [AWS Amplify](https://aws.amazon.com/amplify/)
 - [GitHub Pages](https://pages.github.com/)

**Comment by bezael** [comment]
I would consider it appropriate [Firebase](https://firebase.com) as well.
