### ISSUE TITLE
Make the React project

### ISSUE THREAD

**Issue by AngelGarcia13** [AngelGarcia13/DominicanWhoCodes#9]
The idea behind DominicanWho.Codes was use this project to learn how to use the main JS front-end frameworks.

That's why I'm doing the same thing with React.

**Comment by dionnyprensa** [comment]
Will any API be exposed?

**Comment by AngelGarcia13** [comment]
> Will any API be exposed?

In the next major release, let's make the MVP in Blazor first and them we will start working on the other projects, and will be adding tasks for move the JSON data to an API

**Comment by AngelGarcia13** [comment]
Hey @dionnyprensa go and check out the Roadmap!

**Comment by GianCastle** [comment]
Our organization was able to clone the functionality in React. The link to the repository is https://github.com/React-Dominicana/dominicans-who-code-react

However, we still need to address some issues! :P

**Comment by AngelGarcia13** [comment]
> Our organization was able to clone the functionality in React. The link to the repository is https://github.com/React-Dominicana/dominicans-who-code-react
> 
> However, we still need to address some issues! :P

Hey! Can you please add the React project's info to the README (see how is structured now) like the Vue.js project.

**Comment by Jadhielv** [comment]
> 
> 
> > Our organization was able to clone the functionality in React. The link to the repository is https://github.com/React-Dominicana/dominicans-who-code-react
> > However, we still need to address some issues! :P
> 
> Hey! Can you please add the React project's info to the README (see how is structured now) like the Vue.js project.

Done @AngelGarcia13, check PR #143
